### ISSUE TITLE
How to get raw html from an OGElement?

### ISSUE THREAD

**Issue by hankinsoft** [thomasdenney/ObjectiveGumbo#2]
I can get the text easily enough, but I cannot figure out a way to get the raw underlying html from an OGElement? Is that possible at the moment?

**Comment by programmingthomas** [comment]
Not currently possible but I intend to add it.

**Comment by hankinsoft** [comment]
Cool, I just wanted to make sure I wasn't missing something obvious! I've got a workaround in the meantime. Thanks for the great library btw.

**Comment by programmingthomas** [comment]
OK, this is now supported.
