### ISSUE TITLE
Publish to CocoaPod

### ISSUE THREAD

**Issue by julien-c** [thomasdenney/ObjectiveGumbo#4]
Would it be hard?

Thanks!

**Comment by programmingthomas** [comment]
I'm planning to do it over the weekend.

**Comment by julien-c** [comment]
Great! 

Do you think it would be hard to build an HTML-to-NSAttributedText converter (to use with iOS 7's super-powerful new Text Kit) built on Gumbo?

**Comment by programmingthomas** [comment]
That's a really interesting idea. Gumbo doesn't do any CSS parsing so unfortunately things like <b style="font-weight:normal">this would normally be bold but isn't</b> would still end up being bold. Secondly, ObjectiveGumbo supports iOS 5+ so I would rather integration be done through Core Text instead (and NSAttributedString requires iOS 6+). ObjectiveGumbo also supports OSX and I believe OSX currently doesn't have Text Kit (Mavericks might, but I'm not sure).

NSAttributedString isn't currently a priority for me (CocoaPods and AFNetworking integration are, however) but if you or anyone else wants to fork the project to work on integration that would be really awesome.

**Comment by programmingthomas** [comment]
I've now added a podspec and I am awaiting the CocoaPods folks to merge the pull request :).
